name: app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1

environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  html: ^0.15.4
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  path_provider: ^2.0.15
  flutter_local_notifications: ^19.5.0
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html: ^0.15.1
  page_flip: ^0.2.0
  webview_flutter: ^4.9.0
  webview_flutter_web: ^0.2.2+4
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.0
  intl: 0.20.2
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - img/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "img/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "img/logo.png"